sudo: false

language: go

env:
  - GO111MODULE=on

go:
  - 1.16.x

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0
  - go mod vendor

script:
  - golangci-lint run
  - go test -v -race  -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
